# Generated by Django 5.0.7 on 2024-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacion', '0003_representacion_creacion_representacion_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representacion',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
