# Generated by Django 5.0.7 on 2024-07-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
