# Generated by Django 5.0.7 on 2024-07-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_miembro_creacion_miembro_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
