# Generated by Django 5.0.7 on 2024-07-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_alter_miembro_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
