@hostname = localhost
@port = 8000
@host = http://{{hostname}}:{{port}}


##############################################################
# @no-cookie-jar
# @no-redirect
GET /gabinete HTTP/1.1

##############################################################
GET /gabinete/1 HTTP/1.1

##############################################################
GET /gabinete/2 HTTP/1.1

##############################################################
GET /gabinete/3 HTTP/1.1

##############################################################
GET /gabinete/4 HTTP/1.1
