# Generated by Django 5.0.7 on 2024-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'init_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
