# Generated by Django 5.0.7 on 2024-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Evento',
        ),
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
