# Generated by Django 5.0.7 on 2024-08-15 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100, verbose_name='Denominacion')),
                ('color', models.CharField(max_length=9, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Partido Politico',
                'verbose_name_plural': 'Partidos Politicos',
                'db_table': 'public_political_parties',
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('image', models.ImageField(upload_to='functionaries/avatar', verbose_name='Avatar')),
                ('height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nivel')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='public.functionary', verbose_name='Superior')),
                ('political_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='political_party', to='public.politicalparty', verbose_name='Partido Politico')),
            ],
            options={
                'verbose_name': 'Funcionario Publico',
                'verbose_name_plural': 'Funcionarios Publicos',
                'db_table': 'public_functionaries',
            },
        ),
        migrations.CreateModel(
            name='FunctionaryPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=4096, verbose_name='Biografia')),
                ('image', models.ImageField(upload_to='functionaries/profile', verbose_name='Foto Perfil')),
                ('functionary', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='public.functionary')),
            ],
            options={
                'verbose_name': 'Funcionario Publico - Perfil',
                'verbose_name_plural': 'Funcionarios Publicos - Perfiles',
                'db_table': 'public_functionary_profiles',
            },
        ),
    ]
