# Generated by Django 5.0.7 on 2024-08-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionaryperfil',
            name='functionary',
        ),
        migrations.DeleteModel(
            name='Functionary',
        ),
        migrations.DeleteModel(
            name='FunctionaryPerfil',
        ),
    ]
