# Generated by Django 5.0.7 on 2024-08-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0002_remove_functionaryperfil_functionary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
    ]
