# Generated by Django 5.0.7 on 2024-08-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representation',
        ),
    ]
