# Generated by Django 5.0.7 on 2024-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
