# Generated by Django 5.0.7 on 2024-08-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_representante_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
