# Generated by Django 5.0.7 on 2024-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0007_delete_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('numero_miembro', models.CharField(max_length=20)),
                ('zona', models.CharField(choices=[('CABA', 'CABA'), ('PBA', 'PBA'), ('Salta', 'Salta'), ('Corrientes', 'Corrientes'), ('Córdoba', 'Córdoba'), ('Neuquen', 'Neuquén'), ('Mendoza', 'Mendoza'), ('Chubut', 'Chubut')], max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('actividad', models.CharField(max_length=255)),
                ('zona', models.CharField(max_length=100)),
            ],
        ),
    ]
