# Generated by Django 5.0.7 on 2024-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
    ]
