# Generated by Django 5.0.7 on 2024-07-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacionCivil', '0002_asociacioncivil_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociacioncivil',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asociacioncivil',
            name='modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
