# Generated by Django 5.0.7 on 2024-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacionCivil', '0003_asociacioncivil_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociacioncivil',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
